// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbyvQZBc7RC1Ctth2E1V_1PgOjit-gubo',
    appId: '1:646232894556:web:ebe571b77374d12267ca99',
    messagingSenderId: '646232894556',
    projectId: 'llmstethoscope-e226c',
    authDomain: 'llmstethoscope-e226c.firebaseapp.com',
    storageBucket: 'llmstethoscope-e226c.appspot.com',
    measurementId: 'G-78J42887KP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGwNYpjY_D9Ku6VkDULpF5P_SOygrfsuo',
    appId: '1:646232894556:android:a77cbbff2f7bfe9667ca99',
    messagingSenderId: '646232894556',
    projectId: 'llmstethoscope-e226c',
    storageBucket: 'llmstethoscope-e226c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs99oauW9HT8BcRdKCSp7J7R3ksoI4XoU',
    appId: '1:646232894556:ios:8bde0293063fe0ae67ca99',
    messagingSenderId: '646232894556',
    projectId: 'llmstethoscope-e226c',
    storageBucket: 'llmstethoscope-e226c.appspot.com',
    iosBundleId: 'com.example.llmtestapp.llmStethoscope',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs99oauW9HT8BcRdKCSp7J7R3ksoI4XoU',
    appId: '1:646232894556:ios:c6929c99d426bd9a67ca99',
    messagingSenderId: '646232894556',
    projectId: 'llmstethoscope-e226c',
    storageBucket: 'llmstethoscope-e226c.appspot.com',
    iosBundleId: 'com.example.llmtestapp.llmStethoscope.RunnerTests',
  );
}
